// Compile-time routing tables at the sizes the P2 paper measures: every table shape at
// m = 10, 100 and 1,000, and the GitHub API table. The route lists and queries in the other
// headers of this directory are generated by the paper's harness (gen_route_tests); the
// expected route and values of each query come from the harness's reference matcher, not
// from this library.
//
// Each table is built twice, while compiling (make_static_table) and at run time
// (build_table), and both answer every query. A compiler that cannot evaluate a table within
// the budget this directory's CMakeLists.txt gives it fails to build the test.
#pragma once

#include <gtest/gtest.h>

#include <array>
#include <cstdint>
#include <span>
#include <string_view>

#include <matcher/route.hpp>

namespace ct_tables
{
	struct Probe
	{
		unsigned method;
		std::string_view path;
		std::uint32_t route;  // 0xFFFFFFFF: no route
		std::array<std::string_view, 4> caps;
		std::uint8_t ncaps;
	};

	template <auto& Routes, auto& Probes>
	void check()
	{
		using namespace matcher::route;
		static constexpr auto compiled = make_static_table<Routes>();
		const Built run = build_table(std::span<const RouteSpec>(Routes));
		ASSERT_EQ(run.error, BuildError::None);
		for (const Probe& p : Probes)
		{
			for (const TableView& view : {compiled.view(), run.view()})
			{
				const Match m = find(view, p.method, p.path);
				const std::uint32_t got = m.status == Status::Found ? m.route : 0xFFFFFFFFu;
				SCOPED_TRACE(p.path);
				EXPECT_EQ(got, p.route);
				if (got == p.route && m.status == Status::Found)
				{
					ASSERT_EQ(m.count, p.ncaps);
					for (std::uint8_t i = 0; i < m.count; ++i)
					{
						EXPECT_EQ(m.params[i].view(), p.caps[i]);
					}
				}
			}
		}
	}
}  // namespace ct_tables
